services:
  db:
    restart: always
    image: mariadb
    environment:
      - MYSQL_USER=optuna
      - MYSQL_PASSWORD=optuna
      - MYSQL_DATABASE=optuna
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3309:3306"
  aif360:
    build: ./aif360
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    ports:
      - "8888:8888"
      - "6006:6006"
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=mysql+mysqlconnector://optuna:optuna@db/optuna

